name: RecipePlugin
version: '${project.version}'
main: org.secretlife.recipeplugin.RecipePlugin
api-version: '1.20'

commands:
  removeprotection:
    description: Removes high level protection enchants from players.
    usage: /<command>